version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: gradle
    directory: "/api-app"
    schedule:
      interval: "daily"
  - package-ecosystem: npm
    directory: "/web-app"
    schedule:
      interval: "daily"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
        update-types:
          - "major"
          - "minor"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
