version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: gradle
    directory: "/api-app"
    schedule:
      interval: "daily"
  - package-ecosystem: npm
    directory: "/web-app"
    schedule:
      interval: "daily"
    ignore:
      # TODO Remove ignoring React 19
      #   Azure MSAL currently does not support React 19
      #   See https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/7577
      - dependency-name: react:*
        versions: [">=19.0.0"]
      - dependency-name: react-dom:*
        versions: [">=19.0.0"]
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
        update-types:
          - "major"
          - "minor"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
