services:
  proxy:
    build: proxy
    depends_on:
      - web-app
      - api-app
    ports:
      - "8080:8080"

  web-app:
    build: web-app
    ports:
      - "8081:80"

  api-app:
    build: api-app
    env_file:
      - .env.local
    ports:
      - "8082:8080"
    volumes:
      - store-data:/app/data

volumes:
  store-data:
