services:
  proxy:
    build: proxy
    depends_on:
      - web-app
      - api-app
    ports:
      - "3000:8080"

  web-app:
    build: web-app
    ports:
      - "8081:80"

  api-app:
    build: api-app
    depends_on:
      - database
    env_file:
      - .env
      - path: .env.local
        required: false
    ports:
      - "8082:8080"

  database:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
