apiVersion: schema.esdm.io/core/v1
kind: external-system
name: calendar
scope:
  domain: activity-sampling
direction: inbound
---
apiVersion: schema.esdm.io/core/v1
kind: external-system
name: timesheet
scope:
  domain: activity-sampling
direction: outbound
---
apiVersion: schema.esdm.io/core/v1
kind: external-system
name: notifications
scope:
  domain: activity-sampling
direction: bidirectional
