@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_LANDSCAPE()

title "Container Diagram for Activity Sampling System"

Person(softwareDeveloper, "Software Developer", "Wants to track his/her activities.")
Person(productOwner, "Product Owner", "Wants to analyze the effort.")

System_Boundary(activitySampling, "Activity Sampling System") {
  Container_Ext(proxy, "Proxy", "Nginx", "Handles the incoming requests.")
  Container(webApp, "Static Web App", "TypeScript, React", "Provides a graphical user interface for the API.")
  Container(apiApp, "API App", "Java, Spring", "Handles all the business logic and data storage.")
  Container(desktopApp, "Desktop App", "TypeScript, Electron", "Combines a graphical user interface and handling the business logic and datas storage.")
  ContainerDb_Ext(eventStore, "Event　Store", "Filesystem, CSV", "Stores the logged activities.")

  Rel(proxy, webApp, "Delivers", "HTTPS")
  Rel(proxy, apiApp, "Routes public endpoints", "HTTPS")
  Rel(webApp, apiApp, "Uses", "JSON/HTTPS")
  Rel(apiApp, eventStore, "Record activities", "File")
  Rel(desktopApp, eventStore, "Record activities", "File")
}

Rel(softwareDeveloper, proxy, "Log activity", "HTTPS")
Rel(softwareDeveloper, desktopApp, "Log activity")

Rel(productOwner, proxy, "Analyze effort", "HTTPS")
Rel(productOwner, desktopApp, "Analyze effort")

SHOW_FLOATING_LEGEND()
@enduml
