apiVersion: schema.esdm.io/core/v1
kind: domain
name: activity-sampling
description: Periodically asks the user about their current activity and logs it for analysis.
---
apiVersion: schema.esdm.io/core/v1
kind: process-manager
name: timer
scope:
  domain: activity-sampling
deliveryGuarantee: at-most-once
correlatedBy:
  source: event-field
  field: timer
state:
  type: object
  properties:
    interval:
      type: string
      format: duration
    nextElapseAt:
      type: string
      format: date-time
startsWhen:
  - boundedContext: activity-sampling
    aggregate: timer
    event: started
endsWhen:
  - name: program-exit
    condition: The program exits.
timers:
  - name: progress
    after:
      value: 1
      unit: seconds
reactions:
  - when:
      boundedContext: activity-sampling
      aggregate: timer
      event: started
    rule: Start the timer.
    setTimers:
      - progress
  - when:
      boundedContext: activity-sampling
      aggregate: timer
      event: stopped
    rule: Stop the timer.
    cancelTimers:
      - progress
  - when:
      timer: progress
    rule: Tick the timer.
    emits:
      - boundedContext: activity-sampling
        aggregate: timer
        command: tick
---
apiVersion: schema.esdm.io/core/v1
kind: event-handler
name: notification
scope:
  domain: activity-sampling
deliveryGuarantee: at-most-once
handles:
  - boundedContext: activity-sampling
    aggregate: logged-activity
    event: activity-logged
  - boundedContext: activity-sampling
    aggregate: timer
    event: elapsed
sideEffects:
  - type: other
    rule: Notify the user that the current interval has elapsed.
---
apiVersion: schema.esdm.io/core/v1
kind: event-handler
name: write-timesheet-csv
scope:
  domain: activity-sampling
deliveryGuarantee: at-most-once
handles:
  - boundedContext: activity-sampling
    aggregate: logged-activity
    event: timesheet-exported
sideEffects:
  - type: external-call
    externalSystem: timesheet
    rule: Write the timesheet for the exported period as a CSV file in Harvest format.
---
apiVersion: schema.esdm.io/core/v1
kind: external-system
name: calendar
scope:
  domain: activity-sampling
direction: inbound
category: calendar
capabilities:
  - Provides information about holidays and vacations.
---
apiVersion: schema.esdm.io/core/v1
kind: external-system
name: timesheet
scope:
  domain: activity-sampling
direction: outbound
category: csv-export
