@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_LANDSCAPE()

title "Container Diagram for Activity Sampling System"

Person(softwareDeveloper, "Software Developer", "Wants to track his/her activities.")
Person(productOwner, "Product Owner", "Wants to analyze the effort.")

System_Boundary(activitySampling, "Activity Sampling System") {
  Container_Ext(proxy, "Proxy", "Nginx", "Handles the incoming requests.")
  Container(webApp, "Static Web App", "TypeScript, React", "Provides a graphical user interface for the API.")
  Container(apiApp, "API App", "Java, Spring", "Handles all the business logic and data storage.")
  ContainerDb_Ext(database, "Database", "Filesystem, CSV", "Stores the logged activities.")

  Rel(proxy, webApp, "Delivers", "HTTPS")
  Rel(proxy, apiApp, "Routes public endpoints", "HTTPS")
  Rel_Up(webApp, apiApp, "Uses", "JSON/HTTPS")
  Rel(apiApp, database, "Record activities", "SQL/TCP")
}

Rel(softwareDeveloper, proxy, "Log activity", "HTTPS")
Rel(productOwner, proxy, "Analyze effort", "HTTPS")

SHOW_FLOATING_LEGEND()
@enduml
