@startuml

title "Events for Activity Sampling System"

class TimerStarted {
  timestamp: Timestamp
  interval: Duration
}

class IntervalElapsed {
  timestamp: Timestamp
}

class ActivityLogged {
  timestamp: Timestamp
  duration: Duration
  client: String
  project: String
  task: String
  notes?: String
}

@enduml
