@startuml
[Application] <<..application..>>
[Domain] <<..domain..>>
[Infrastructure] <<..infrastructure..>>
[UI] <<..ui..>>
[Common] <<..common..>>

[UI] --> [Application]
[UI] --> [Domain]
[UI] --> [Common]
[Application] --> [Domain]
[Application] --> [Infrastructure]
[Application] --> [Common]
[Domain] --> [Common]
[Infrastructure] --> [Domain]
[Infrastructure] --> [Common]
@enduml
