spring:
  application:
    name: api-app
  datasource:
    url: jdbc:postgresql://localhost:5432/activitysampling
    username:
    password:

management:
  endpoints:
    web:
      exposure:
        include: "*"
