spring:
  application:
    name: api-app

app:
  activities:
    capacity: PT40H
  csv-activities-store:
    file: data/activity-log.csv
  csv-holiday-repository:
    file: data/holidays.csv

server:
  servlet:
    session:
      cookie:
        same-site: lax
      timeout: PT60M
