INSERT INTO activities (timestamp, duration, client, project, task, notes)
VALUES ('2025-01-17 09:30 Europe/Berlin',
        INTERVAL '30' MINUTE,
        'ACME Inc.',
        'Foobar',
        'Do something',
        NULL),
       ('2025-01-16 17:00 Europe/Berlin',
        INTERVAL '30' MINUTE,
        'ACME Inc.',
        'Foobar',
        'Do something',
        NULL),
       ('2025-01-16 16:30 Europe/Berlin',
        INTERVAL '30' MINUTE,
        'ACME Inc.',
        'Foobar',
        'Do something',
        NULL),
       ('2025-01-16 16:00 Europe/Berlin',
        INTERVAL '30' MINUTE,
        'ACME Inc.',
        'Foobar',
        'Make things',
        'This is a note');
