apiVersion: schema.esdm.io/core/v1
kind: aggregate
name: activity
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
identifiedBy:
  source: static
  value: nothing
state:
  type: object
  properties:
    start:
      type: string
      format: date
    finish:
      type: string
      format: date
    client:
      type: string
    project:
      type: string
    task:
      type: string
    category:
      type: string
    hours:
      type: string
      format: duration
    cycleTime:
      type: number
  required: [start, finish, client, project, task, hours, cycleTime]
invariants:
  - name: natural-key
    rule: Use client, project, task and category as combined key for an activity.
  - name: non-empty-client
    rule: The client must not be empty or contains only whitespaces.
  - name: non-empty-project
    rule: The project must not be empty or contains only whitespaces.
  - name: non-empty-task
    rule: The task must not be empty or contains only whitespaces.
  - name: total-hours
    rule: Calculate the total sum of hours per task.
  - name: cycle-time
    rule: Calculate the cycle time for each task as difference between finish and start.
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: log-activity
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: activity
data:
  type: object
  properties:
    timestamp:
      type: string
      format: date-time
    duration:
      type: string
      format: duration
    client:
      type: string
    project:
      type: string
    task:
      type: string
    notes:
      type: string
    category:
      type: string
  required: [timestamp, duration, client, project, task]
constraints:
  - name: non-empty-client
    rule: Client must not be empty.
  - name: non-empty-project
    rule: Project must not be empty.
  - name: non-empty-task
    rule: Task must not be empty.
  - name: valid-duration
    rule: Duration must be greater than zero.
publishes:
  - logged
actors:
  - software-developer
  - notifier
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: export-timesheet
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: activity
data:
  type: object
  properties:
    timesheets:
      type: array
      items:
        type: TimesheetEntry
    filename:
      type: string
  required: [timesheets, filename]
publishes:
  - timesheet-exported
actors:
  - software-developer
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: logged
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: activity
data:
  type: object
  properties:
    timestamp:
      type: string
      format: date-time
    duration:
      type: string
      format: duration
    client:
      type: string
    project:
      type: string
    task:
      type: string
    notes:
      type: string
    category:
      type: string
    notification:
      type: string
  required: [timestamp, duration, client, project, task, notification]
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: timesheet-exported
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: activity
data:
  type: object
  properties:
    filename:
      type: string
    timesheets:
      type: array
      items:
        type: TimesheetData
    required: [filename, timesheets]
