apiVersion: schema.esdm.io/core/v1
kind: aggregate
name: activity
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
identifiedBy:
  source: state
  field: id
state:
  type: object
  properties:
    id:
      type: number
    start:
      type: string
      format: date
    finish:
      type: string
      format: date
    client:
      type: string
    project:
      type: string
    task:
      type: string
    category:
      type: string
    hours:
      type: string
      format: duration
  required: [start, finish, client, project, task, hours]
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: log-activity
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: activity
data:
  type: object
  properties:
    timestamp:
      type: string
      format: date-time
    duration:
      type: string
      format: duration
    client:
      type: string
    project:
      type: string
    task:
      type: string
    notes:
      type: string
    category:
      type: string
  required: [timestamp, duration, client, project, task]
publishes:
  - logged
actors:
  - software-developer
  - notifier
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: export-timesheet
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: activity
data:
  type: object
  properties:
    timesheets:
      type: array
      items:
        type: TimesheetEntry
    filename:
      type: string
  required: [timesheets, filename]
publishes:
  - timesheet-exported
actors:
  - software-developer
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: logged
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: activity
data:
  type: object
  properties:
    timestamp:
      type: string
      format: date-time
    duration:
      type: string
      format: duration
    client:
      type: string
    project:
      type: string
    task:
      type: string
    notes:
      type: string
    category:
      type: string
    notification:
      type: string
  required: [timestamp, duration, client, project, task]
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: timesheet-exported
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: activity
data:
  type: object
  properties:
    filename:
      type: string
    timesheets:
      type: array
      items:
        type: TimesheetData
    required: [filename, timesheets]
