apiVersion: schema.esdm.io/core/v1
kind: aggregate
name: activity-log
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
identifiedBy:
  source: state
  field: timestamp
state:
  type: object
  properties:
    timestamp:
      type: string
      format: date-time
    duration:
      type: string
      format: duration
    client:
      type: string
    project:
      type: string
    task:
      type: string
    notes:
      type: string
    category:
      type: string
  required: [timestamp, duration, client, project, task]
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: log-activity
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: activity-log
data:
  type: object
  properties:
    timestamp:
      type: string
      format: date-time
    duration:
      type: string
      format: duration
    client:
      type: string
    project:
      type: string
    task:
      type: string
    notes:
      type: string
    category:
      type: string
  required: [timestamp, duration, client, project, task]
publishes:
  - activity-logged
actors:
  - software-developer
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: activity-logged
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: activity-log
data:
  type: object
  properties:
    timestamp:
      type: string
      format: date-time
    duration:
      type: string
      format: duration
    client:
      type: string
    project:
      type: string
    task:
      type: string
    notes:
      type: string
    category:
      type: string
  required: [timestamp, duration, client, project, task]
