apiVersion: schema.esdm.io/core/v1
kind: bounded-context
name: activity-sampling
scope:
  domain: activity-sampling
---
apiVersion: schema.esdm.io/core/v1
kind: actor
name: software-developer
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
type: human
responsibilities:
  - Want to track his/her activities.
---
apiVersion: schema.esdm.io/core/v1
kind: actor
name: product-owner
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
type: human
responsibilities:
  - Wants to analyze the effort.
---
apiVersion: schema.esdm.io/core/v1
kind: actor
name: timer
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
type: system
responsibilities:
  - Periodically triggers the prompt asking the user about the current activity.
---
apiVersion: schema.esdm.io/core/v1
kind: actor
name: calendar
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
type: system
backedBy:
  - calendar
responsibilities:
  - Receives calendar updates from the external system and triggers synchronization commands.
