apiVersion: schema.esdm.io/core/v1
kind: external-system
name: calendar
scope:
  domain: activity-sampling
direction: inbound
category: calendar
capabilities:
  - Provides information about holidays and vacations.
---
apiVersion: schema.esdm.io/core/v1
kind: aggregate
name: calendar
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
identifiedBy:
  source: static
  value: default
state:
  type: object
  properties:
    holidays:
      type: array
      items:
        type: object
        properties:
          date:
            type: string
            format: date
          title:
            type: string
          duration:
            type: string
            format: duration
        required: [date, title]
    vacation:
      type: array
      items:
        type: object
        properties:
          date:
            type: string
            format: date
          duration:
            type: string
            format: duration
        required: [date]
  required: [holidays, vacation]
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: sync-holidays
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: calendar
data:
  type: array
  items:
    type: object
    properties:
      date:
        type: string
        format: date
      title:
        type: string
      duration:
        type: string
        format: duration
    required: [date, title]
publishes:
  - holidays-changed
actors:
  - calendar
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: sync-vacation
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: calendar
data:
  type: array
  items:
    type: object
    properties:
      date:
        type: string
        format: date
      duration:
        type: string
        format: duration
    required: [date]
publishes:
  - vacation-changed
actors:
  - calendar
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: holidays-changed
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: calendar
data:
  type: array
  items:
    type: object
    properties:
      date:
        type: string
        format: date
      title:
        type: string
      duration:
        type: string
        format: duration
    required: [date, title]
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: vacation-changed
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: calendar
data:
  type: array
  items:
    type: object
    properties:
      date:
        type: string
        format: date
      duration:
        type: string
        format: duration
    required: [date]
