apiVersion: schema.esdm.io/core/v1
kind: external-system
name: calendar
scope:
  domain: activity-sampling
direction: inbound
category: calendar
capabilities:
  - Provides information about holidays and vacations.
---
apiVersion: schema.esdm.io/core/v1
kind: aggregate
name: calendar
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
identifiedBy:
  source: static
  value: default
state:
  type: object
  properties:
    holidays:
      type: array
      items:
        type: Holiday
    vacation:
      type: array
      items: Vacation
  required: [holidays, vacation]
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: sync-holidays
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: calendar
data:
  type: array
  items:
    type: Holiday
publishes:
  - holidays-changed
actors:
  - calendar
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: holidays-changed
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: calendar
data:
  type: array
  items:
    type: Holiday
---
apiVersion: schema.esdm.io/core/v1
kind: value-object
name: holiday
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
schema:
  type: object
  properties:
    date:
      type: string
      format: date
    title:
      type: string
    duration:
      type: string
      format: duration
  required: [date, title]
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: sync-vacations
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: calendar
data:
  type: array
  items:
    type: object
    properties:
      date:
        type: string
        format: date
      duration:
        type: string
        format: duration
    required: [date]
publishes:
  - vacations-changed
actors:
  - calendar
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: vacations-changed
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: calendar
data:
  type: array
  items:
    type: object
    properties:
      date:
        type: string
        format: date
      duration:
        type: string
        format: duration
    required: [date]
---
apiVersion: schema.esdm.io/core/v1
kind: value-object
name: vacation
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
schema:
  type: object
  properties:
    date:
      type: string
      format: date
    duration:
      type: string
      format: duration
  required: [date]
