apiVersion: schema.esdm.io/core/v1
kind: read-model
name: timesheet
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
projections:
  - boundedContext: activity-sampling
    aggregate: activity
    event: logged
    rule: Append the activity entry to the timesheet.
  - boundedContext: activity-sampling
    aggregate: settings
    event: changed
    rule: Memorize the capacity and categories.
  - boundedContext: activity-sampling
    aggregate: holiday
    event: holidays-changed
    rule: Update the holidays list used for capacity calculation.
  - boundedContext: activity-sampling
    aggregate: vacation
    event: vacations-changed
    rule: Update the vacation list used for capacity calculation.
schema:
  type: object
  properties:
    entries:
      type: array
      items:
        type: object
        properties:
          timestamp:
            type: string
            format: date-time
          duration:
            type: string
            format: duration
          client:
            type: string
          project:
            type: string
          task:
            type: string
          notes:
            type: string
          category:
            type: string
        required: [timestamp, duration, client, project, task]
    holidays:
      type: array
      items:
        type: Holiday
    vacations:
      type: array
      items:
        type: Vacation
    capacity:
      type: string
      format: duration
    categories:
      type: array
      items:
        type: string
  required:
    - entries
    - holidays
    - vacations
    - capacity
    - categories
---
apiVersion: schema.esdm.io/core/v1
kind: query
name: get-recent-activities
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
readModel: timesheet
parameters:
  type: object
  properties:
    today:
      type: string
      format: date
    timezone:
      type: string
  required: [today, timezone]
result:
  type: array
  items:
    type: object
    properties:
      workingDays:
        type: array
        items: WorkingDay
      timeSummary:
        type: TimeSummary
    required: [workingDays, timeSummary]
actors:
  - software-developer
---
apiVersion: schema.esdm.io/core/v1
kind: read-model
name: timer
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
projections:
  - boundedContext: activity-sampling
    aggregate: timer
    event: started
    rule: Set running and reset progress.
  - boundedContext: activity-sampling
    aggregate: timer
    event: stopped
    rule: Set non-running.
  - boundedContext: activity-sampling
    aggregate: timer
    event: ticked
    rule: Update progress.
  - boundedContext: activity-sampling
    aggregate: timer
    event: elapsed
    rule: Memorize timestamp and duration of current interval.
schema:
  type: object
  properties:
    isRunning:
      type: boolean
    elapsedTime:
      type: string
      format: duration
    progress:
      type: number
  required: [isRunning, elapsedTime, progress]
---
apiVersion: schema.esdm.io/core/v1
kind: query
name: get-current-interval
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
readModel: timer
result:
  type: object
  properties:
    isRunning:
      type: boolean
    elapsedTime:
      type: string
      format: duration
    progress:
      type: number
  required: [isRunning, elapsedTime, progress]
actors:
  - software-developer
---
apiVersion: schema.esdm.io/core/v1
kind: read-model
name: settings
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
projections:
  - boundedContext: activity-sampling
    aggregate: settings
    event: changed
    rule: Update the settings.
schema:
  type: object
  properties:
    capacity:
      type: string
      format: duration
    categories:
      type: array
      items:
        type: string
    firstName:
      type: string
    lastName:
      type: string
  required: [capacity, categories]
---
apiVersion: schema.esdm.io/core/v1
kind: query
name: get-categories
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
readModel: settings
result:
  type: object
  properties:
    categories:
    type: array
    items:
      type: string
  required:
    - categories
---
apiVersion: schema.esdm.io/core/v1
kind: read-model
name: report
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
projections:
  - boundedContext: activity-sampling
    aggregate: activity
    event: logged
    rule:
      Join activity entries with same client, project, task and category into a single entry, update
      start and finish, and accumulate hours.
  - boundedContext: activity-sampling
    aggregate: activity
    event: logged
    rule: Collect a list of all categories for filtering in the statistics query.
schema:
  type: object
  properties:
    activities:
      type: array
      items:
        type: object
        properties:
          start:
            type: string
            format: date-time
            description: The timestamp when the first activity in the entry was logged in UTC.
          finish:
            type: string
            format: date-time
            description: The timestamp when the last activity in the entry was logged in UTC.
          client:
            type: string
          project:
            type: string
          task:
            type: string
          category:
            type: string
          hours:
            type: string
            format: duration
        required: [start, finish, client, project, task, hours]
    categories:
      type: array
      items:
        type: string
  required: [activities, categories]
---
apiVersion: schema.esdm.io/core/v1
kind: query
name: get-report
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
readModel: report
parameters:
  type: object
  properties:
    scope:
      type: string
      enum: [clients, projects, tasks, categories]
    # TODO remove from and to parameters because start and finish can be before or after and hours or cycle time are only relevant for done activities
    from:
      type: string
      format: date
    to:
      type: string
      format: date
    timezone:
      type: string
  required: [scope, timezone]
result:
  type: object
  properties:
    entries:
      type: array
      items:
        type: ReportEntry
    totalHours:
      type: string
      format: duration
  required: [entries, totalHours]
actors:
  - product-owner
---
apiVersion: schema.esdm.io/core/v1
kind: query
name: get-statistics
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
readModel: report
parameters:
  type: object
  properties:
    scope:
      type: string
      enum: [workingHours, cycleTime]
    categories:
      type: array
      items:
        type: string
    timezone:
      type: string
  required: [scope]
result:
  type: object
  properties:
    histogram:
      type: array
      items:
        type: Histogram
    median:
      type: Median
    categories:
      type: array
      items:
        type: string
    totalCount:
      type: integer
  required: [histogram, median, categories, totalCount]
actors:
  - product-owner
---
apiVersion: schema.esdm.io/core/v1
kind: query
name: get-estimate
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
readModel: report
parameters:
  type: object
  properties:
    categories:
      type: array
      items:
        type: string
    timezone:
      type: string
result:
  type: object
  properties:
    cycleTimes:
      type: array
      items:
        type: EstimateEntry
    categories:
      type: array
      items:
        type: string
    totalCount:
      type: integer
  required: [cycleTimes, categories, totalCount]
actors:
  - product-owner
---
apiVersion: schema.esdm.io/core/v1
kind: query
name: get-burn-up
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
readModel: report
parameters:
  type: object
  properties:
    from:
      type: string
      format: date
    to:
      type: string
      format: date
    categories:
      type: array
      items:
        type: string
    timeZone:
      type: string
  required: [from, to, categories, timeZone]
result:
  type: object
  properties:
    data:
      type: array
      items:
        type: BurnUpData
    totalThroughput:
      type: integer
    categories:
      type: array
      items:
        type: string
  required: [data, totalThroughput, categories]
actors:
  - product-owner
---
apiVersion: schema.esdm.io/core/v1
kind: query
name: get-timesheet
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
readModel: timesheet
parameters:
  type: object
  properties:
    from:
      type: string
      format: date
    to:
      type: string
      format: date
    today:
      type: string
      format: date
    timezone:
      type: string
  required: [from, to, today, timezone]
result:
  type: object
  properties:
    entries:
      type: array
      items:
        type: TimesheetEntry
    totalHours:
      type: string
      format: duration
    capacity:
      type: Capacity
  required: [entries, totalHours, capacity]
actors:
  - software-developer
