apiVersion: schema.esdm.io/core/v1
kind: aggregate
name: timer
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
identifiedBy:
  source: static
  value: default
state:
  type: {}
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: start
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    interval:
      type: string
      format: duration
      default: "PT30M"
  required: [interval]
publishes:
  - started
actors:
  - software-developer
constraints:
  - name: positive-interval
    rule: Interval must be greater than zero.
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: stop
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: {}
publishes:
  - stopped
actors:
  - software-developer
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: tick
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    isElapsed:
      type: boolean
    duration:
      type: string
      format: duration
    progressedTime:
      type: string
      format: duration
  required: [isElapsed, duration]
constraints:
  - name: tick-or-elapse
    rule:
      If isElapsed is true, elapsed is emitted, otherwise progressedTime must be provided and ticked
      is emitted.
publishes:
  - ticked
  - elapsed
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: started
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    interval:
      type: string
      format: duration
    timer:
      type: string
    notification:
      type: string
  required: [interval, timer, notification]
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: stopped
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    timer:
      type: string
  required: [timer]
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: ticked
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    progressedTime:
      type: string
      format: duration
    duration:
      type: string
      format: duration
    timer:
      type: string
  required: [progressedTime, duration, timer]
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: elapsed
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    duration:
      type: string
      format: duration
    notification:
      type: string
  required: [duration, timer, notification]
