apiVersion: schema.esdm.io/core/v1
kind: aggregate
name: timer
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
identifiedBy:
  source: static
  value: default
state:
  type: object
  properties:
    currentInterval:
      type: string
      format: duration
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: start
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    interval:
      type: string
      format: duration
  required: [interval]
publishes:
  - started
actors:
  - software-developer
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: stop
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data: {}
publishes:
  - stopped
actors:
  - software-developer
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: elapse-interval
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data: {}
publishes:
  - interval-elapsed
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: started
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    timer:
      type: string
    timestamp:
      type: string
      format: date-time
    interval:
      type: string
      format: duration
  required: [timer, timestamp, interval]
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: stopped
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    timer:
      type: string
  required: [timer]
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: interval-elapsed
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    timer:
      type: string
    timestamp:
      type: string
      format: date-time
    interval:
      type: string
      format: duration
  required: [timer, timestamp, interval]
---
apiVersion: schema.esdm.io/core/v1
kind: event-handler
name: notify-interval-elapsed
scope:
  domain: activity-sampling
deliveryGuarantee: at-most-once
handles:
  - boundedContext: activity-sampling
    aggregate: timer
    event: interval-elapsed
sideEffects:
  - type: other
    rule: Notify the user that the current interval has elapsed.
