apiVersion: schema.esdm.io/core/v1
kind: aggregate
name: timer
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
identifiedBy:
  source: static
  value: default
state:
  type: object
  properties:
    interval:
      type: string
      format: duration
    nextElapseAt:
      type: string
      format: date-time
  required: [intervaö]
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: start
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    interval:
      type: string
      format: duration
  required: [interval]
publishes:
  - started
actors:
  - software-developer
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: started
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    timer:
      type: string
    interval:
      type: string
      format: duration
  required: [timer, interval]
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: stop
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: null
publishes:
  - stopped
actors:
  - software-developer
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: stopped
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    timer:
      type: string
  required: [timer]
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: tick
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: null
publishes:
  - ticked
  - elapsed
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: ticked
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    timer:
      type: string
    elapsedTime:
      type: string
      format: duration
  required: [timer]
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: elapsed
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    timer:
      type: string
    timestamp:
      type: string
      format: date-time
    duration:
      type: string
      format: duration
  required: [timer, timestamp, duration]
---
apiVersion: schema.esdm.io/core/v1
kind: event-handler
name: notify-timer-elapsed
scope:
  domain: activity-sampling
deliveryGuarantee: at-most-once
handles:
  - boundedContext: activity-sampling
    aggregate: timer
    event: elapsed
sideEffects:
  - type: other
    rule: Notify the user that the current interval has elapsed.
---
apiVersion: schema.esdm.io/core/v1
kind: process-manager
name: timer
scope:
  domain: activity-sampling
deliveryGuarantee: at-most-once
correlatedBy:
  source: event-field
  field: timer
state:
  type: null
startsWhen:
  - boundedContext: activity-sampling
    aggregate: timer
    event: started
endsWhen:
  - name: timer-stopped
    condition: Stop command is received.
timers:
  - name: progress
    after:
      value: 1
      unit: seconds
reactions:
  - when:
      boundedContext: activity-sampling
      aggregate: timer
      event: started
    rule: Start the timer.
    setTimers:
      - progress
  - when:
      boundedContext: activity-sampling
      aggregate: timer
      event: stopped
    rule: Stop the timer.
    cancelTimers:
      - progress
  - when:
      timer: progress
    rule: Tick the timer.
    emits:
      - boundedContext: activity-sampling
        aggregate: timer
        command: tick
