CREATE TABLE activities (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start    TIMESTAMP WITH TIME ZONE NOT NULL,
  duration INTERVAL SECOND(12)      NOT NULL,
  client   VARCHAR(200)             NOT NULL,
  project  VARCHAR(200)             NOT NULL,
  task     VARCHAR(200)             NOT NULL,
  notes    VARCHAR(500)
);

CREATE UNIQUE INDEX activities_timestamp_unique on activities (start);
