apiVersion: schema.esdm.io/core/v1
kind: process-manager
name: notifier
scope:
  domain: activity-sampling
deliveryGuarantee: at-most-once
correlatedBy:
  source: event-field
  field: notification
state:
  type: object
  properties:
    lastActivity:
      type: LoggedActivity
    duration:
      type: string
      format: duration
invariants:
  - name: last-activity-stored
    rule: Try reading last activity from store when no last activity is known.
  - name: missing-last-activity
    rule: Open the app when the user clicks on the notification and no last activity is stored.
startsWhen:
  - boundedContext: activity-sampling
    aggregate: timer
    event: started
endsWhen:
  - name: stop-timer
    condition: The timer is stopped.
reactions:
  - when:
      boundedContext: activity-sampling
      aggregate: activity
      event: logged
    rule: Store last activity and hide notification.
  - when:
      boundedContext: activity-sampling
      aggregate: timer
      event: elapsed
    rule: Read current duration and show notification with last activity if any.
    emits:
      - boundedContext: activity-sampling
        aggregate: activity
        command: log-activity
