apiVersion: schema.esdm.io/core/v1
kind: process-manager
name: notifier
scope:
  domain: activity-sampling
deliveryGuarantee: at-most-once
correlatedBy:
  source: event-field
  field: notification
state:
  type: object
  properties:
    lastActivity:
      type: LoggedActivity
startsWhen:
  - boundedContext: activity-sampling
    aggregate: timer
    event: elapsed
endsWhen:
  - name: close-notification
    condition: The notification is closed.
reactions:
  - when:
      boundedContext: activity-sampling
      aggregate: logged-activity
      event: activity-logged
    rule: Store last activity.
  - when:
      boundedContext: activity-sampling
      aggregate: timer
      event: elapsed
    rule: Show notification with last activity.
    emits:
      - boundedContext: activity-sampling
        aggregate: logged-activity
        command: log-activity
