apiVersion: schema.esdm.io/core/v1
kind: event-handler
name: timesheet-exporter
scope:
  domain: activity-sampling
deliveryGuarantee: at-most-once
handles:
  - boundedContext: activity-sampling
    aggregate: logged-activity
    event: timesheet-exported
sideEffects:
  - type: external-call
    externalSystem: timesheet
    rule: Write the timesheet for the exported period as a CSV file in Harvest format.
