apiVersion: schema.esdm.io/core/v1
kind: bounded-context
name: activity-sampling
scope:
  domain: activity-sampling
---
apiVersion: schema.esdm.io/core/v1
kind: actor
name: software-developer
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
type: human
responsibilities:
  - Want to track his/her activities.
---
apiVersion: schema.esdm.io/core/v1
kind: actor
name: product-owner
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
type: human
responsibilities:
  - Wants to analyze the effort.
---
apiVersion: schema.esdm.io/core/v1
kind: actor
name: calendar
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
type: system
responsibilities:
  - Receives calendar updates from the external system and triggers synchronization commands.
backedBy:
  - calendar
---
apiVersion: schema.esdm.io/core/v1
kind: external-system
name: calendar
scope:
  domain: activity-sampling
direction: inbound
category: calendar
capabilities:
  - Provides information about holidays and vacations.
