apiVersion: schema.esdm.io/core/v1
kind: aggregate
name: timer
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
identifiedBy:
  source: static
  value: default
state:
  type: null
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: start
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    interval:
      type: string
      format: duration
  required: [interval]
publishes:
  - started
actors:
  - software-developer
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: stop
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: null
publishes:
  - stopped
actors:
  - software-developer
---
apiVersion: schema.esdm.io/core/v1
kind: command
name: tick
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    isElapsed:
      type: boolean
    duration:
      type: string
      format: duration
    elapsedTime:
      type: string
      format: duration
    timestamp:
      type: string
      format: date-time
      description: The elapse time in UTC.
  required: [isElapsed, duration]
constraints:
  - name: tick-or-elapse
    rule: If isElapsed is true, timestamp must be provided, otherwise elapsedTime must be provided.
publishes:
  - ticked
  - elapsed
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: elapsed
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    timer:
      type: string
    timestamp:
      type: string
      format: date-time
    duration:
      type: string
      format: duration
  required: [timer, timestamp, duration]
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: started
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    timer:
      type: string
    interval:
      type: string
      format: duration
  required: [timer, interval]
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: stopped
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    timer:
      type: string
  required: [timer]
---
apiVersion: schema.esdm.io/core/v1
kind: event
name: ticked
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
  aggregate: timer
data:
  type: object
  properties:
    timer:
      type: string
    elapsedTime:
      type: string
      format: duration
    duration:
      type: string
      format: duration
  required: [timer, elapsedTime, duration]
