apiVersion: schema.esdm.io/core/v1
kind: value-object
name: working-day
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
schema:
  type: object
  properties:
    date:
      type: string
      format: date
    activities:
      type: array
      items:
        type: RecentActivity
---
apiVersion: schema.esdm.io/core/v1
kind: value-object
name: recent-activity
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
schema:
  type: object
  properties:
    time:
      type: string
      format: time
    client:
      type: string
    project:
      type: string
    task:
      type: string
    notes:
      type: string
    category:
      type: string
  required: [time, client, project, task]
---
apiVersion: schema.esdm.io/core/v1
kind: value-object
name: time-summary
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
schema:
  type: object
  properties:
    today:
      type: string
      format: duration
    yesterday:
      type: string
      format: duration
    thisWeek:
      type: string
      format: duration
    thisMonth:
      type: string
      format: duration
  required: [today, yesterday, thisWeek, thisMonth]

---
apiVersion: schema.esdm.io/core/v1
kind: value-object
name: timesheet-entry
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
schema:
  type: object
  properties:
    date:
      type: string
      format: date
    client:
      type: string
    project:
      type: string
    task:
      type: string
    hours:
      type: string
      format: duration
  required: [date, client, project, task, hours]
---
apiVersion: schema.esdm.io/core/v1
kind: value-object
name: timesheet-data
scope:
  domain: activity-sampling
  boundedContext: activity-sampling
schema:
  type: object
  properties:
    date:
      type: string
      format: date
    client:
      type: string
    project:
      type: string
    task:
      type: string
    notes:
      type: string
    hours:
      type: number
    firstName:
      type: string
    lastName:
      type: string
  required: [date, client, project, task, hours, firstName, lastName]
