name: Release

on: push
#  push:
#    tags:
#      - "v*.*.*"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Set up Node.js LTS
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
      - name: Build package
        run: make dist
      - name: Set OS‑specific distribution file
        run: |
          case $RUNNER_OS in
            Linux) echo "DIST_FILE=./dist/*.deb" >> $GITHUB_ENV ;;
            macOS) echo "DIST_FILE=./dist/*.dmg" >> $GITHUB_ENV ;;
            Windows) echo "DIST_FILE=./dist/*.exe" >> $GITHUB_ENV ;;
          esac
      - name: Create release
        run: gh release create v1.2.3 --generate-notes --prerelease ${{ env.DIST_FILE }}
        #run: gh release create v1.2.3 --notes-from-tag ./dist/*.deb ./dist/*.dmg ./dist/*.exe
