name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
      - name: Create release
        run: gh release create ${{ github.ref_name }} --verify-tag --generate-notes --draft
  upload-assets:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    env:
      CSC_LINK: ${{ secrets.MAC_CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.MAC_CSC_KEY_PASSWORD }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      GH_TOKEN: ${{ github.token }}
      MAC_SIGN: true
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Set up Node.js LTS
        uses: actions/setup-node@v7
        with:
          node-version: "lts/*"
      - name: Build distribution file
        shell: bash
        run: make dist
      - name: Determine OS‑specific distribution file
        shell: bash
        run: |
          case $RUNNER_OS in
            Linux) echo "DIST_FILE=./dist/*.deb" >> $GITHUB_ENV ;;
            macOS) echo "DIST_FILE=./dist/*.dmg" >> $GITHUB_ENV ;;
            Windows) echo "DIST_FILE=./dist/*.exe" >> $GITHUB_ENV ;;
          esac
      - name: Upload distribution file
        shell: bash
        run: |
          gh release upload ${{ github.ref_name }} ${{ env.DIST_FILE }}
